version: '3.7'
services:
    mongo:
        image: mongo
        restart: "no"
        ports:
            - '6000:27017'
        volumes:
            - mongo:/data/db
        env_file:
            - .env.local

    cache:
        image: redis:7-alpine
        restart: "no"
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data

volumes:
    mongo:
        driver: local
    cache:
        driver: local
