version: '3.7'
services:
    mongo:
        image: mongo
        volumes:
            - mongo:/data/db

    cache:
        image: redis:7-alpine
        
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data

    recipes:
        build:
            context: .
        
        ports:
            - '3000:3000'
        depends_on:
            - mongo
            - cache
        links:
            - mongo
            - cache
        volumes:
            - ./:/usr/src/app

volumes:
    mongo:
        driver: local
    cache:
        driver: local
